---

  - name: install package for horizon
    tags: horizon, ubuntu
    apt:
      name: openstack-dashboard
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: edit file for local_settings.py
    tags: horizon, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      regexp: 'OPENsTACK_HOST = "127.0.0.1"'
      line: 'OPENSTACK_HOST = "controller"'

  - name: verify file for local_settings.py
    tags: horizon, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      line: "'OPENSTACK_HOST = '*'"
      state: present
    check_mode: yes

  - name: edit file for local_settings.py(1)
    tags: horizon, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      regexp: "SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'"
      line: "SESSION_ENGINE = 'django.contrib.sessions.backends.cache'"

  - name: edit file for local_settings.py(2)
    tags: horizon, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      regexp: 'OPENSTACK_KEYSTONE_URL = "http://%s/identity/v3" % OPENSTACK_HOST'
      line: 'OPENSTACK_KEYSTONE_URL = "http://%s:5000/identity/v3" % OPENSTACK_HOST'
      state: present
    check_mode: yes

  - name: add conf file for local_settings.py(2)
    tags: neutron, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      line: "OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True"
      state: present

  - name: add conf file for local_settings.py(3)
    tags: neutron, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      line: 'OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = "Default"'
      state: present

  - name: add conf file for local_settings.py(4)
    tags: neutron, ubuntu, edit
    lineinfile:
      path: /etc/openstack-dashboard/local_settings.py
      line: 'OPENSTACK_KEYSTONE_DEFAULT_ROLE = "user"'
      state: present

  - name: apache2.service restart
    service:
      name: apache2.service
      state: restarted
